# Creating numpy/n-d array

In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3=np.zeros((2,3))
arr3 #float data type by default

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4=np.ones((3,4))
arr4 #float data type by default

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr5=np.identity(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [14]:
arr6=np.arange(7,14)
arr6

array([ 7,  8,  9, 10, 11, 12, 13])

In [15]:
arr7=np.arange(10,20,2)
arr7

array([10, 12, 14, 16, 18])

In [18]:
arr8=np.linspace(1,9,3)
arr8 #will give points with equidistance

array([1., 5., 9.])

In [19]:
arr9=np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [31]:
arr10=arr9.copy()
arr10[0]=12 #this change will not reflact in arr9 unlike list
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# properties and attributes

In [33]:
arr1.shape

(5,)

In [34]:
arr2.shape

(2, 3)

In [38]:
arr11=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
arr11.shape


(2, 2, 2)

In [39]:
arr11.ndim

3

In [40]:
arr11.size

8

In [44]:
arr11.dtype

dtype('int64')

In [46]:
arr11.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

# indexing, slicing and iteration

In [48]:
arr12=np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
arr12.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
arr12[2:] #all same as the list

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [55]:
arr13=np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
arr13[:,2] #2nd column of all the rows

array([ 2,  6, 10, 14, 18, 22])

In [59]:
arr13[:,1:3] #1st and 2nd columns of all the rows

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [87]:
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# numpy operations

In [67]:
arr14=np.array([1,2,3,4,5,6])
arr15=np.array([7,8,9,10,11,12])

In [68]:
arr14-arr15

array([-6, -6, -6, -6, -6, -6])

In [69]:
arr14*arr15

array([ 7, 16, 27, 40, 55, 72])

In [70]:
arr14*2

array([ 2,  4,  6,  8, 10, 12])

In [71]:
arr14>3

array([False, False, False,  True,  True,  True])

In [73]:
arr16=np.arange(6).reshape(2,3)
arr17=np.arange(6,18).reshape(3,4)

In [76]:
arr18=arr16.dot(arr17) #simple matrix multiplication
arr18

array([[ 38,  41,  44,  47],
       [128, 140, 152, 164]])

In [79]:
arr18.max()

np.int64(164)

In [81]:
arr18.min()

np.int64(38)

In [84]:
arr18.max(axis=0) #give me maximum elements columns wise

array([128, 140, 152, 164])

In [86]:
arr18.max(axis=1) #give me maximum elements row wise

array([ 47, 164])

# Reshaping numpy array

In [89]:
arr18.ravel() #convert higher dimentional array to 1-d array

array([ 38,  41,  44,  47, 128, 140, 152, 164])

In [90]:
arr18.transpose()

array([[ 38, 128],
       [ 41, 140],
       [ 44, 152],
       [ 47, 164]])

# fancy indexing

In [96]:
arr19=np.arange(10,30).reshape(5,4)
arr19

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [97]:
arr19[[0,2,4]] #give 0th,2nd,4th row 

array([[10, 11, 12, 13],
       [18, 19, 20, 21],
       [26, 27, 28, 29]])