# TensorFlow basics

In [1]:
import tensorflow as tf

## Creating tensors

In [6]:
st=tf.Variable("I am Kalp", tf.string)
num=tf.Variable(324,tf.int16)
fl=tf.Variable(3.24,tf.float64)

## Rank/Degree of Tensors

In [8]:
t1=tf.Variable([['a','b','c'],['d','e','f']],tf.string)
tf.rank(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
t1.shape

TensorShape([2, 2])

## changing the shape

In [19]:
tensor1=tf.ones([3]) #1-d array with size 3
tensor2=tf.ones([1,3]) #one 2-d array containing one 1-d array of size 3
tensor3=tf.ones([1,2,3]) #one 2-d array containing two 1-d array each of size 3
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [28]:
tensor4=tf.reshape(tensor3,[2,3,1]) #tot ele=2*3*1=6 so this number must be equal with the tot elements in the tensor3
print(tensor4)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [27]:
tensor5=tf.reshape(tensor3,[2,3])
print(tensor5)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [25]:
tensor6=tf.reshape(tensor3,[3,-1])
print(tensor6)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
